export const ACTIVITY_UI_COPY = {
  openPanelAriaLabel: "Abrir panel de actividad",
  toolsLabelPlural: "herramientas",
  defaultActivityLabel: "Actividad",
  lifecycleFallback: "sistema",
  statusFallback: "estado",
} as const;

export const ACTIVITY_LABELS: Record<string, string> = {
  // system
  start: "Iniciando",
  end: "Finalizando",
  lifecycle: "Sistema",
  status: "Estado",
  // agent
  thinking: "Pensando",
  planning: "Planificando",
  orchestrator: "Orquestador",
  agent: "Agente",
  spawn_agent: "Delegando a agente",
  spawn: "Delegando a agente",
  // terminal
  bash: "Terminal",
  shell: "Terminal",
  shell_execute: "Terminal",
  run_shell_command: "Terminal",
  execute_command: "Terminal",
  run_command: "Terminal",
  // search
  web_search: "Búsqueda web",
  search_code: "Buscar en código",
  grep: "Buscar texto",
  find_files: "Buscar archivos",
  // files
  read_text_file: "Leer archivo",
  read_file: "Leer archivo",
  write_file: "Escribir archivo",
  write_text_file: "Escribir archivo",
  create_file: "Crear archivo",
  delete_file: "Eliminar archivo",
  move_file: "Mover archivo",
  patch_file: "Parchear archivo",
  apply_patch: "Aplicar cambios",
  list_directory: "Listar directorio",
  directory_tree: "Árbol de directorio",
  create_directory: "Crear directorio",
  make_directory: "Crear directorio",
  mkdir: "Crear directorio",
  remove_directory: "Eliminar directorio",
  rename_file: "Renombrar archivo",
  copy_file: "Copiar archivo",
  read_directory: "Leer directorio",
  list_files: "Listar archivos",
  // repo
  clone_repository: "Clonar repositorio",
  // code
  run_tests: "Ejecutar tests",
  generate_code: "Generar código",
  code_gen: "Generar código",
  code_generation: "Generar código",
  // schedule
  schedule_task: "Programar tarea",
  schedule: "Programar tarea",
  create_schedule: "Crear tarea programada",
  list_schedules: "Listar tareas",
  delete_schedule: "Eliminar tarea",
  cron: "Tarea programada",
};

export const ARG_KEY_LABELS: Record<string, string> = {
  command: "Comando",
  cmd: "Comando",
  shell_command: "Shell",
  script: "Script",
  path: "Ruta",
  file_path: "Archivo",
  directory: "Directorio",
  input: "Entrada",
  input_message: "Tarea",
  input_messages: "Mensajes",
  query: "Consulta",
  content: "Contenido",
  code: "Código",
  messages: "Mensajes",
  repo_url: "Repositorio",
  repo_path: "Ruta repo",
  pattern: "Patrón",
  text: "Texto",
  language: "Lenguaje",
  timeout: "Tiempo límite",
};
